### ISSUE TITLE
Error: Timestamp is null

### ISSUE THREAD

**Issue by gregorskii** [mirkokiefer/bunyan-cloudwatch#15]
Hi there,

I am seeing this error when running in AWS:

```
InvalidParameterException: 1 validation error detected: Value null at 'logEvents.1.member.timestamp' failed to satisfy constraint: Member must not be null
    at Request.extractError (/api/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/api/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/api/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/api/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/api/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /api/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/api/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/api/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/api/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/api/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/api/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/api/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /api/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/api/node_modules/aws-sdk/lib/request.js:37:9)
```

I have configured the logger like so:

```
module.exports = function() {

    var bunyan = require('bunyan'),
        Bunyan2Loggly = require('bunyan-loggly').Bunyan2Loggly,
        bformat = require('bunyan-format'),
        formatOut = bformat({ outputMode: 'short' }),
        log
    ;

    if (process.env.NODE_ENV === 'local') {
        log = bunyan.createLogger({'name': 'LOCAL', stream: formatOut});
    } else {
        log = bunyan.createLogger({
            name: process.env.LOGGLY_ALIAS.replace('.%s', ''),
            streams: [
                {
                    level: 'error',
                    type: 'raw',
                    stream: new Bunyan2Loggly({
                        token: process.env.LOGGLY_TOKEN,
                        subdomain: process.env.LOGGLY_SUBDOMAIN
                    })
                },
                {
                    level: 'fatal',
                    type: 'raw',
                    stream: require('bunyan-cloudwatch')({
                        logGroupName: process.env.OPSGENIE_CW_GROUP,
                        logStreamName: 'service-api-ops-cloudwatch-stream',
                        cloudWatchLogsOptions: {
                            accessKeyId: process.env.AWS_KEY,
                            secretAccessKey: process.env.AWS_SECRET,
                            region: process.env.AWS_REGION
                        }
                    })
                }
            ]
        });
    }

    return log;

};

```

Using the logger:

```
log.fatal('TESTING CLOUDWATCH');
```

Thanks

**Comment by torgeir** [comment]
Same thing here. Did you find a workaround @gregorskii ?

**Comment by torgeir** [comment]
For the record, setting `{ stream: cloudwatchStream, type: "raw" }` fixed this issue for me 🎉 
https://github.com/mirkokiefer/bunyan-cloudwatch/pull/16#issuecomment-210065905

**Comment by mirkokiefer** [comment]
As specified in the readme `type: 'raw'` always needs to be set.

**Comment by gregorskii** [comment]
I believe I had raw set, correct?

**Comment by mirkokiefer** [comment]
Ah true was mislead by the comment below - you were not able to resolve the issue @gregorskii ?

**Comment by gregorskii** [comment]
I fixed it in #16. Dunno if it's the best way to do it, but it worked.

**Comment by mirkokiefer** [comment]
Hm thats weird - maybe you can test with the latest version. Its testing with bunyan 2.0 now.

**Comment by RavidAshurov** [comment]
I am having the same issue. 

I am using the "raw" options and the following package versions:
"bunyan": "^1.8.15",
"bunyan-cloudwatch": "^2.2.0",
"bunyan-format": "^0.2.1"
